core/apps/urls.py
from django.urls import path
from core.apps.views.subsidios.views import *
from core.homepage.views.usuarios.views import UsuarioCreateView
from core.apps.views.dashboard.views import DashBoardView

app_name = 'apps'

urlpatterns = [
    #Inicio
    path('dashboard/', DashBoardView.as_view(),name='dashboard'),
    #LIstados
    #gas licuado
    path('subsidio/gas/listado/', SubsidioGasListView.as_view(),name='subsidio_gas_lista'),
    #energia electrica
    path('subsidio/luz/listado/', SubsidioLuzListView.as_view(),name='subsidio_luz_lista'),
    #servicio agua
    path('subsidio/agua/listado/', SubsidioAguaListView.as_view(),name='subsidio_agua_lista'),
    path('subsidio/agua/agregar/', SubsidioAguaCreateView.as_view(),name='subsidio_agua_create'),
    #transporte publico
    path('subsidio/transporte/listado/', SubsidioTrasnporteListView.as_view(),name='subsidio_transporte_lista'),
    path('subsidio/transporte/agregar/', SubsidioTransporteCreateView.as_view(),name='subsidio_transporte_create'),
    path('subsidio/transporte/formulario/', SubsidioTransporteFormView.as_view(),name='subsidio_transporte_form'),

]

primer_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views.homepage.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.homepage.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('apps/', include('core.apps.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root='settings.MEDIA_ROOT')

core/apps/views/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

class DashBoardView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['panel'] = 'Panel de administrador'
        context['titulo'] = 'Panel de administrador'
        context['subtitulo'] = 'Bienvenido al panel de administrador'
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!--Header-->
        {% include 'header.html' %}
        <!--Content-->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">

                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascrpit -->
    {% block javascript %}
    
    {% endblock %}
    </body>
{% endblock %}

templates/dashboard.html
{% extends 'vista_admin/body.html' %}

templates/footer.html
{% load static %}
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      2021
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2021 <a href="https://adminlte.io"></a>.</strong> All rights reserved.
  </footer>

templates/form.html
{% extends 'layout.html' %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit   "></i>
                    {% endif %}
                    {{ titulo }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="frecuencia_uso">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="summit" class="btn btn-primary btn-flat btnTest">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
            </div>
        </div>
    </form>
{% endblock %}
    {% block javascript %}
        <script>
            {% if form.errors %}
                var errors = '';
                {% for field in form %}
                    {% for error in field.errors %}
                        errors += '\n{{ error }}';
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    errors += '\n{{ error }}';
                {% endfor %}
                Swal.fire({
                    title: 'Error!',
                    text: errors,
                    icon: 'error',
                });
            {% endif %}
            $('form').on('submit', function (e) {
                e.preventDefault()
                var parametros = $(this).serializeArray()
                    .ajax({
                        url: '{% url 'apps:subsidio_agua_lista'%}',
                        type: 'POST',
                        data: parametros,
                        dataType: 'json'
                    }).done(function (data) {
                        console.log(data);
                        if (!data.hasOwnProperty('error')) {
                            location.href = '{{ list_url }}'
                            return false
                        }
                        message_error(data.error);
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                        alert(textStatus + ": " + errorThrown)
                    }).always(function (data) {

                    });
            });
            /*alert_jqueryconfirm();*/
        </script>
    {% endblock %}

templates/header.html
{% load static %}
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="{% url 'index' %}" class="navbar-brand">
        <img src="{% static  '../static/lib/AdminLTE-3.1.0/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Sistema subsidios</span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="." class="nav-link">Inicio</a>
          </li>
          {% comment %}<li class="nav-item">
            <a href="#" class="nav-link">Contact</a>
          </li>{% endcomment %}
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Mantenimiento</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
              <li><a href="#" class="dropdown-item">Verificacion </a></li>
              <li><a href="#" class="dropdown-item">Datos</a></li>

              <li class="dropdown-divider"></li>
              {% comment %}
              <!-- Level two dropdown-->
              <li class="dropdown-submenu dropdown-hover">
                <a id="dropdownSubMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle">Hover for action</a>
                <ul aria-labelledby="dropdownSubMenu2" class="dropdown-menu border-0 shadow">
                  <li>
                    <a tabindex="-1" href="#" class="dropdown-item">level 2</a>
                  </li>

                  <!-- Level three dropdown-->
                  <li class="dropdown-submenu">
                    <a id="dropdownSubMenu3" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle">level 2</a>
                    <ul aria-labelledby="dropdownSubMenu3" class="dropdown-menu border-0 shadow">
                      <li><a href="#" class="dropdown-item">3rd level</a></li>
                      <li><a href="#" class="dropdown-item">3rd level</a></li>
                    </ul>
                  </li>
                  <!-- End Level three -->

                  <li><a href="#" class="dropdown-item">level 2</a></li>
                  <li><a href="#" class="dropdown-item">level 2</a></li>
                </ul>
              </li>
              <!-- End Level two -->{% endcomment %}
            </ul>
          </li>
        </ul>

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
       <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ panel }}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static '../static/lib/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet"
          href="{% static '../static/lib/AdminLTE-3.1.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '../static/lib/AdminLTE-3.1.0/dist/css/adminlte.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '../static/lib/AdminLTE-3.1.0/css/adminlte.min.css' %}">
    <!-- Jquery -->
    <script src="{% static '../static/lib/AdminLTE-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static '../../static/lib/AdminLTE-3.1.0/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static '../static/lib/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static '../static/lib/AdminLTE-3.1.0/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static '../static/lib/AdminLTE-3.1.0/js/demo.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static '../static/lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static '../static/lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static '../static/lib/sweetalert2-9.10.0/sweetalert2.all.js' %}"></script>
    <!-- Functions -->
    <script src="{% static '../static/js/function.js' %}"></script>

    <!--Block head-->
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}

</body>
</html>

templates/layout.html
{% extends 'body.html' %}

templates/lista.html
{% extends 'vista_admin/body.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static '../static/lib/DataTables/DataTables-1.10.25/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static '../static/lib/AdminLTE-3.1.0/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static '../static/lib/DataTables/DataTables-1.10.25/js/jquery.dataTables.js' %}"></script>
    <script src="{% static '../static/lib/DataTables/DataTables-1.10.25/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static '../static/lib/AdminLTE-3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static '../static/lib/AdminLTE-3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>

{% endblock %}
{% block head_list %}

{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ titulo }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="data">
                <thead>

                {% block columnas %}
                {% endblock %}

                </thead>
                <tbody>

                {% block filas %}
                {% endblock %}

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Ejemplo
            </button>
        </div>
    </div>
{% endblock %}

<!-- Block para dataTable-->
{% block javascript %}

    <script>
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'apps:subsidio_transporte_lista' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data)
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ": " + errorThrown)
                }).always(function (data) {

                });
            });
        });
    </script>

{% endblock %}