core/apps/urls.py
from django.urls import path
from core.apps.views.subsidios.views import *
from core.homepage.views.usuarios.views import UsuarioCreateView
from core.apps.views.dashboard.views import DashBoardView

app_name = 'apps'

urlpatterns = [
    #Inicio
    path('dashboard/', DashBoardView.as_view(),name='dashboard'),
    #LIstados
    #gas licuado
    path('subsidio/gas/listado/', SubsidioGasListView.as_view(),name='subsidio_gas_lista'),
    #energia electrica
    path('subsidio/luz/listado/', SubsidioLuzListView.as_view(),name='subsidio_luz_lista'),
    #servicio agua
    path('subsidio/agua/listado/', SubsidioAguaListView.as_view(),name='subsidio_agua_lista'),
    path('subsidio/agua/agregar/', SubsidioAguaCreateView.as_view(),name='subsidio_agua_create'),
    #transporte publico
    path('subsidio/transporte/listado/', SubsidioTrasnporteListView.as_view(),name='subsidio_transporte_lista'),
    path('subsidio/transporte/agregar/', SubsidioTransporteCreateView.as_view(),name='subsidio_transporte_create'),
    path('subsidio/transporte/formulario/', SubsidioTransporteFormView.as_view(),name='subsidio_transporte_form'),

]

core/homepage/urls.py
from django.urls import path
from core.homepage.views.homepage.views import *
from core.homepage.views.usuarios.views import *

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('homepage/',UsuarioCreateView.as_view(),name='homepage'),
]

primer_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views.homepage.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.homepage.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('apps/', include('core.apps.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root='settings.MEDIA_ROOT')

core/homepage/models.py
from django.db import models

# Create your models here.

core/homepage/views/homepage/views.py
# Create your views here.
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Sistema Subidios - Index'
        context['titulo'] = ''

        return context

core/homepage/views/usuarios/views.py
from django.http import JsonResponse
from django.views.generic import CreateView

from core.homepage.form import UsuarioForm
from core.apps.models import Usuario


class UsuarioCreateView(CreateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'usuarios/homepage.html'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'autocomplete':
                data = []
                for i in Usuario.objects.filter(dui__icontains=request.POST['term']):
                    data.append(i.toJSON())
        except Exception as error:
            data['error'] = str(error)
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Sistema Subidios - Index'
        context['titulo'] = 'Registro de subsidios'

        return context

core/homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{{ panel }}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static '../static/lib/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300 i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
    <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{% static '../../static/lib/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '../../static/lib/AdminLTE-3.1.0/dist/css/adminlte.min.css' %}">
    {% block librerias %}


    {% endblock %}
</head>

<body>

<!-- ======= Top Bar ======= -->
<div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
        <div class="contact-info mr-auto">
            <!--<i class="icofont-envelope"></i> <a href="mailto:contact@example.com">contact@example.com</a>
            <i class="icofont-phone"></i> +1 5589 55488 55-->
        </div>
    </div>
</div>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="#hero">Sistema Subsidios<span>.</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt=""></a>-->

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="#hero"><i class="bx bx-home"></i> Inicio</a></li>
                <li><a href="#registro"><i class="fab fa-wpforms"></i> Registro</a></li>
                <li><a href="#consulta"><i class="bx bx-search-alt"></i> Consulta</a></li>
                <li>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'apps:dashboard' %}">
                            <i class="fas fa-door-open"></i> Ir panel administrador</a>
                    {% else %}
                        <a href="{% url 'login' %}">
                            <i class="bx bx-log-in"></i> Login</a>
                    {% endif %}
                </li>


            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
        <h1>Bienvenido a <span>Sistema Subsidios</span></h1>
        <h2>Sistema para el registro de subsidios recibidos por la población salvadoreña</h2>
        <div class="d-flex">
            <a href="#registro" class="btn-get-started scrollto">Iniciar registro</a>
            <!--<a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox btn-watch-video" data-vbtype="video" data-autoplay="true"> Watch Video <i class="icofont-play-alt-2"></i></a> -->
        </div>
    </div>
</section>
<!-- End Hero -->

<main id="main">

    <!-- ======= Services Section ======= -->
    <section id=services" class="featured-services">
        <div class="container" data-aos="fade-up">

            <div class="row">
                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                        <div class="icon"><i class="fas fa-tint"></i></div>
                        <h4 class="title"><a href="">Subsidio Agua</a></h4>
                        <p class="description">El subsidio de agua potable y/o alcantarillado es un beneficio que
                            entrega el Estado,
                            a través de las municipalidades, para ayudar a las familias más necesitadas del país.</p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
                        <div class="icon"><i class="nav-icon fas fa-bolt"></i></div>
                        <h4 class="title"><a href="">Subsidio Energía Eléctrica</a></h4>
                        <p class="description">Las familias que consumen menos de 105 KWh al mes, gozanran del subsidio
                            a la
                            energía eléctrica que otorga el Gobierno Central para apoyar a las personas más
                            necesitadas.</p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
                        <div class="icon"><i class="nav-icon fas fa-burn"></i></div>
                        <h4 class="title"><a href="">Subsidio Gas Licuado</a></h4>
                        <p class="description">El monto del subsidio al GLP que otorga el Gobierno de El Salvador
                            apartir de mayo 2021
                            será de US$8.04.</p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                    <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
                        <div class="icon"><i class="nav-icon fas fa-bus-alt"></i></div>
                        <h4 class="title"><a href="">Subsidio Transporte Público</a></h4>
                        <p class="description">El gobierno subsidio $0.04 por cada buses ocupado y $0.02 por cada
                            microbus.</p>
                    </div>
                </div>

            </div>

        </div>
    </section>
    <!-- End Services Section -->

    <!-- ======= Registro Section ======= -->
    <section id="registro" class="about section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Registro</h2>
                <h3>Registra los <span>subsidios</span> que recibes</h3>
                <p></p>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    {% block datosUsuario %}

                    {% endblock %}
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content d-flex flex-column justify-content-center" data-aos="fade-up">
                    {% block subsidios %}
                    {% endblock %}
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-primary">Iniciar Registro</button>
                        </div>
                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-danger">Cancelar Registro</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- End About Section -->

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients section-bg">
        <div class="container" data-aos="zoom-in">

            <div class="row">

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-1.png' %}" class="img-fluid" alt="">
                </div>

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-2.png' %}" class="img-fluid" alt="">
                </div>

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-3.png' %}" class="img-fluid" alt="">
                </div>

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-4.png' %}" class="img-fluid" alt="">
                </div>

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-5.png' %}" class="img-fluid" alt="">
                </div>

                <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
                    <img src="{% static 'homepage/assets/img/clients/client-6.png' %}" class="img-fluid" alt="">
                </div>

            </div>

        </div>
    </section><!-- End Clients Section -->

    <!-- ======= Consulta Section ======= -->
    <section id="consulta" class="services">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Consulta</h2>
                <h3>Consultar <span>Subsidios</span></h3>
                <p></p>
            </div>

            </div>

        </div>
    </section>
    <!-- End Services Section -->
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong><span>Sistema Subsidios</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            2021</a>
        </div>
    </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<!-- Icons -->
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>